//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeBreakProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutU
    {
        public int AboutID { get; set; }
        public string AboutUsContent { get; set; }
        public string AboutUsImage { get; set; }
    }
}
