//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeBreakProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoffeeProduct
    {
        public int CoffeeID { get; set; }
        public string CoffeeName { get; set; }
        public string CoffeeDescription { get; set; }
        public string CoffeeImage { get; set; }
    }
}
